package com.example.myapplication.model

data class Match(
    val match_id: Long,
    val player_slot: Int,
    val radiant_win: Boolean,
    val hero_id: Int,
    val start_time: Long,
    val duration: Int,
    val game_mode: Int,
    val lobby_type: Int,
    val version: String?,
    val kills: Int,
    val deaths: Int,
    val assists: Int,
    val average_rank: Int,
    val xp_per_min: Int,
    val gold_per_min: Int,
    val hero_damage: Int,
    val tower_damage: Int,
    val hero_healing: Int,
    val last_hits: Int,
    val lane: String?,
    val lane_role: String?,
    val is_roaming: Boolean?,
    val cluster: Int,
    val leaver_status: Int,
    val party_size: Int?,
    val hero_variant: Int
)
